### ISSUE TITLE
Allow user to select which GPT model they want to use

### ISSUE THREAD

**Issue by frankie-mur** [kmesiab/ai-code-critic#42]
As I believe I do not have the required model on my account `gpt-4-1106` I am unable to use the app. I believe this should be configurable on the user's end, or possibly another option that will allow me to still use the app. 

<img width="1440" alt="image" src="https://github.com/kmesiab/ai-code-critic/assets/34355192/df31eeae-bbc1-4ed0-87a0-43bbba7c1a4e">

**Comment by kmesiab** [comment]
Agreed. 

I think this would present the perfect time to reconsider whether the current configuration mechanism should be retired and replaced with a mature solution. 

Want to take a crack at it?

**Comment by frankie-mur** [comment]
Sure! Will be a great opportunity to learn more about the fyne framework 🙂

**Comment by kmesiab** [comment]
Ref: link https://github.com/kmesiab/ai-code-critic/issues/27

**Comment by frankie-mur** [comment]
Are we good to close here? change was merged in PR #46

**Comment by kmesiab** [comment]
Yup
