### ISSUE TITLE
Default context timeout causes instant timeout when configuration is fails to load

### ISSUE THREAD

**Issue by kmesiab** [kmesiab/ai-code-critic#43]
https://github.com/kmesiab/ai-code-critic/blob/b04ac5358e914dc70ab3eaa93ce6604b427cbfda/internal/github.go#L73

Setting the default to 0 here will cause an 'instant timeout.'  Perhaps if this value is < 1, we forego the context w/ timeout?

**Comment by frankie-mur** [comment]
Hey @kmesiab, great suggestion here, however I have a question. This function you mentioned above returns on an error. Then in `GetPullRequest(...)`there is
```
timeout, err := GetContextTimeout()
if err != nil {
	return err
}
```
in this case it will break out and never causing this 'instant timeout' I believe. The default value for context timeout is set to 5 seconds in Config struct.

**Comment by kmesiab** [comment]
> in this case it will break out and never causing this 'instant timeout' I believe. The default value for context timeout is set to 5 seconds in Config struct.

You are right, my mistake!
